### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by Skelmis** [AndrewNunnes/Andrew-s-Bot#3]
*`Note, this is just my opinion`*

I feel that it would be wise to go back and review your code, for example within your fun commands there are a few commands which could benefit from a loop, as well as possibly removing the need for hardcoding.

For example, <https://github.com/AndrewNunnes/Spark-Bot/blob/master/cogs/Fun_Commands.py#L246>
Could be changed to:
```python
description =  f"8{'=' * random.randint(1,10)}D"
```

That is just one example, there are more naturally however that's my 2 cents.

**Comment by drewxillimite** [comment]
Yeah for sure, one day Ima refactor them since I haven’t touched some cogs in forever, Im just working on new things for now
